name: Run Go Application (Standard Time)

on:
  schedule:
    - cron: '0 6 * * *'  # Runs every day at 1 AM EST (6 AM UTC)

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PROGRAM_ID: ${{ secrets.PROGRAM_ID }}
      EMAIL: ${{ secrets.EMAIL }}
      PASSWORD: ${{ secrets.PASSWORD }}
      SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
      APP_PASSWORD: ${{ secrets.APP_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22'

      - name: Install dependencies
        run: go mod tidy

      - name: Build
        run: cd src && go build -o ../app

      - name: Run application
        run: ./app
